environment:
  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_NPY: "18"

install:
  # this installs the appropriate Miniconda
  - powershell .\\ci\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
   # download/install OCE from DLR-SC channel
  - conda config --add channels https://conda.anaconda.org/dlr-sc

build: false

test_script:
  - "conda build ci/conda --quiet"
